In [1]:
import pandas as pd

result_df = pd.read_csv(r'C:\Users\clint\Desktop\Research-Paper-Trucks\Initial Proposal\result_df.csv')
county_change_df = pd.read_csv(r'C:\Users\clint\Desktop\Research-Paper-Trucks\Data\entry_exit\COUNTY_change.csv')
result_df

,CRASH_ID,REPORT_STATE,REPORT_DATE,REPORT_SEQ_NO,LOCATION,CITY_CODE,CITY,STATE,COUNTY_CODE,VEHICLES_IN_ACCIDENT,FATALITIES,INJURIES,CRASH_EVENT_SEQ_ID_DESC
0,4860792,CA,20241017,1,34.441682 / -118.568696,NaN,SANTA CLARITA,CA,37.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
1,4860781,CA,20241117,1,ANNADALE AV / 26 FT W J ST,NaN,SANGER,CA,19.0,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
2,4860550,ID,20241206,2,DIVIDE CREEK,NaN,MERIDIAN,ID,1.0,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
3,4860541,ID,20241122,1,BEST BUSINESS AVE,NaN,KUNA,ID,1.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
4,4860302,IL,20241205,2,S WEST ST,NaN,Olney Twp,IL,159.0,4.0,0,0,2:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46313,16220,SD,19970923,1,6TH ST,NaN,SIOUX FALLS,SD,99.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
46314,16111,SD,20000716,1,I-90,NaN,RURAL,SD,93.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
46315,16017,SD,20010203,1,I-29,NaN,RURAL,SD,99.0,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
46316,15968,SD,19990120,1,I-90,NaN,RURAL,SD,99.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE
46317,15953,SD,20010203,1,I-29,NaN,RURAL,SD,103.0,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...

In [2]:
# Dictionary mapping state abbreviations to FIPS codes
state_to_fips = {
    'AL': '01', 'AK': '02', 'AZ': '04', 'AR': '05', 'CA': '06', 'CO': '08', 'CT': '09', 'DE': '10', 'FL': '12',
    'GA': '13', 'HI': '15', 'ID': '16', 'IL': '17', 'IN': '18', 'IA': '19', 'KS': '20', 'KY': '21', 'LA': '22',
    'ME': '23', 'MD': '24', 'MA': '25', 'MI': '26', 'MN': '27', 'MS': '28', 'MO': '29', 'MT': '30', 'NE': '31',
    'NV': '32', 'NH': '33', 'NJ': '34', 'NM': '35', 'NY': '36', 'NC': '37', 'ND': '38', 'OH': '39', 'OK': '40',
    'OR': '41', 'PA': '42', 'RI': '44', 'SC': '45', 'SD': '46', 'TN': '47', 'TX': '48', 'UT': '49', 'VT': '50',
    'VA': '51', 'WA': '53', 'WV': '54', 'WI': '55', 'WY': '56'
}

# Convert state abbreviations to FIPS codes
result_df['STATE_FIPS'] = result_df['STATE'].map(state_to_fips)

result_df

,CRASH_ID,REPORT_STATE,REPORT_DATE,REPORT_SEQ_NO,LOCATION,CITY_CODE,CITY,STATE,COUNTY_CODE,VEHICLES_IN_ACCIDENT,FATALITIES,INJURIES,CRASH_EVENT_SEQ_ID_DESC,STATE_FIPS
0,4860792,CA,20241017,1,34.441682 / -118.568696,NaN,SANTA CLARITA,CA,37.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,06
1,4860781,CA,20241117,1,ANNADALE AV / 26 FT W J ST,NaN,SANGER,CA,19.0,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,06
2,4860550,ID,20241206,2,DIVIDE CREEK,NaN,MERIDIAN,ID,1.0,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16
3,4860541,ID,20241122,1,BEST BUSINESS AVE,NaN,KUNA,ID,1.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16
4,4860302,IL,20241205,2,S WEST ST,NaN,Olney Twp,IL,159.0,4.0,0,0,2:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46313,16220,SD,19970923,1,6TH ST,NaN,SIOUX FALLS,SD,99.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46314,16111,SD,20000716,1,I-90,NaN,RURAL,SD,93.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46315,16017,SD,20010203,1,I-29,NaN,RURAL,SD,99.0,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46316,15968,SD,19990120,1,I-90,NaN,RURAL,SD,99.0,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46317,15953,SD,20010203,1,I-29,NaN,RURAL,SD,103.0,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,46

In [3]:
import pandas as pd

# Display rows with NaN in COUNTY_CODE
nan_rows = result_df[result_df['COUNTY_CODE'].isna()]
print("Rows with NaN in COUNTY_CODE:")

Rows with NaN in COUNTY_CODE:

In [4]:

# Remove rows with NaN in COUNTY_CODE
result_df = result_df.dropna(subset=['COUNTY_CODE'])

# Ensure COUNTY_CODE is three digits and convert to string
result_df['COUNTY_CODE'] = result_df['COUNTY_CODE'].apply(lambda x: f'{int(x):03d}')

C:\Users\clint\AppData\Local\Temp\ipykernel_17952\382507401.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['COUNTY_CODE'] = result_df['COUNTY_CODE'].apply(lambda x: f'{int(x):03d}')

In [5]:
# Print the data type of the COUNTY_CODE column
print("Data type of COUNTY_CODE column:", result_df['COUNTY_CODE'].dtype)

Data type of COUNTY_CODE column: object

In [6]:
result_df

,CRASH_ID,REPORT_STATE,REPORT_DATE,REPORT_SEQ_NO,LOCATION,CITY_CODE,CITY,STATE,COUNTY_CODE,VEHICLES_IN_ACCIDENT,FATALITIES,INJURIES,CRASH_EVENT_SEQ_ID_DESC,STATE_FIPS
0,4860792,CA,20241017,1,34.441682 / -118.568696,NaN,SANTA CLARITA,CA,037,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,06
1,4860781,CA,20241117,1,ANNADALE AV / 26 FT W J ST,NaN,SANGER,CA,019,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,06
2,4860550,ID,20241206,2,DIVIDE CREEK,NaN,MERIDIAN,ID,001,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16
3,4860541,ID,20241122,1,BEST BUSINESS AVE,NaN,KUNA,ID,001,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16
4,4860302,IL,20241205,2,S WEST ST,NaN,Olney Twp,IL,159,4.0,0,0,2:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46313,16220,SD,19970923,1,6TH ST,NaN,SIOUX FALLS,SD,099,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46314,16111,SD,20000716,1,I-90,NaN,RURAL,SD,093,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46315,16017,SD,20010203,1,I-29,NaN,RURAL,SD,099,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46316,15968,SD,19990120,1,I-90,NaN,RURAL,SD,099,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46
46317,15953,SD,20010203,1,I-29,NaN,RURAL,SD,103,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,46

In [7]:
# Drop rows with NaN values in 'STATE_FIPS' or 'COUNTY_CODE'
result_df = result_df.dropna(subset=['STATE_FIPS', 'COUNTY_CODE'])

# Ensure the columns are integers before formatting
result_df['STATE_FIPS'] = result_df['STATE_FIPS'].astype(int)
result_df['COUNTY_CODE'] = result_df['COUNTY_CODE'].astype(int)

# Create the 'fips' column by concatenating 'STATE_FIPS' and 'COUNTY_CODE'
result_df['FIPS'] = result_df['STATE_FIPS'].apply(lambda x: f"{x:02d}") + result_df['COUNTY_CODE'].apply(lambda x: f"{x:03d}")
result_df

C:\Users\clint\AppData\Local\Temp\ipykernel_17952\1586668998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['STATE_FIPS'] = result_df['STATE_FIPS'].astype(int)
C:\Users\clint\AppData\Local\Temp\ipykernel_17952\1586668998.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['COUNTY_CODE'] = result_df['COUNTY_CODE'].astype(int)
C:\Users\clint\AppData\Local\Temp\ipykernel_17952\1586668998.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['FIPS'] = result_df['STATE_FIPS'].apply(lambda x: f"{x:02d}") + result_df['COUNTY_CODE'].apply(lambda x: f"{x:03d}")

,CRASH_ID,REPORT_STATE,REPORT_DATE,REPORT_SEQ_NO,LOCATION,CITY_CODE,CITY,STATE,COUNTY_CODE,VEHICLES_IN_ACCIDENT,FATALITIES,INJURIES,CRASH_EVENT_SEQ_ID_DESC,STATE_FIPS,FIPS
0,4860792,CA,20241017,1,34.441682 / -118.568696,NaN,SANTA CLARITA,CA,37,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,6,06037
1,4860781,CA,20241117,1,ANNADALE AV / 26 FT W J ST,NaN,SANGER,CA,19,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,6,06019
2,4860550,ID,20241206,2,DIVIDE CREEK,NaN,MERIDIAN,ID,1,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16,16001
3,4860541,ID,20241122,1,BEST BUSINESS AVE,NaN,KUNA,ID,1,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16,16001
4,4860302,IL,20241205,2,S WEST ST,NaN,Olney Twp,IL,159,4.0,0,0,2:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,17,17159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46313,16220,SD,19970923,1,6TH ST,NaN,SIOUX FALLS,SD,99,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46314,16111,SD,20000716,1,I-90,NaN,RURAL,SD,93,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46093
46315,16017,SD,20010203,1,I-29,NaN,RURAL,SD,99,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46316,15968,SD,19990120,1,I-90,NaN,RURAL,SD,99,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46317,15953,SD,20010203,1,I-29,NaN,RURAL,SD,103,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,46,46103

We observe our summary statistics

In [8]:
summary_statistics = result_df[['VEHICLES_IN_ACCIDENT', 'FATALITIES', 'INJURIES']].describe()

# Calculate the value corresponding to z-score = 2
z_score_2_values = summary_statistics.loc['mean'] + 2 * summary_statistics.loc['std']

# Display the summary statistics and z-score = 2 values
summary_statistics.loc['z_score_2'] = z_score_2_values
summary_statistics

           VEHICLES_IN_ACCIDENT    FATALITIES      INJURIES
count              46070.000000  46155.000000  46155.000000
mean                   2.302214      0.046127      0.533203
std                    1.021734      0.266127      1.019588
min                    0.000000      0.000000      0.000000
25%                    2.000000      0.000000      0.000000
50%                    2.000000      0.000000      0.000000
75%                    2.000000      0.000000      1.000000
max                   58.000000     20.000000     35.000000
z_score_2              4.345682      0.578381      2.572380

In [9]:


# Filter the dataframe for FATALITIES
#fatalities_filtered_df = result_df[result_df['FATALITIES'] > z_score_2_values['FATALITIES']]
fatalities_filtered_df = result_df
fatalities_filtered_df

,CRASH_ID,REPORT_STATE,REPORT_DATE,REPORT_SEQ_NO,LOCATION,CITY_CODE,CITY,STATE,COUNTY_CODE,VEHICLES_IN_ACCIDENT,FATALITIES,INJURIES,CRASH_EVENT_SEQ_ID_DESC,STATE_FIPS,FIPS
0,4860792,CA,20241017,1,34.441682 / -118.568696,NaN,SANTA CLARITA,CA,37,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,6,06037
1,4860781,CA,20241117,1,ANNADALE AV / 26 FT W J ST,NaN,SANGER,CA,19,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,6,06019
2,4860550,ID,20241206,2,DIVIDE CREEK,NaN,MERIDIAN,ID,1,2.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16,16001
3,4860541,ID,20241122,1,BEST BUSINESS AVE,NaN,KUNA,ID,1,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16,16001
4,4860302,IL,20241205,2,S WEST ST,NaN,Olney Twp,IL,159,4.0,0,0,2:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,17,17159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46313,16220,SD,19970923,1,6TH ST,NaN,SIOUX FALLS,SD,99,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46314,16111,SD,20000716,1,I-90,NaN,RURAL,SD,93,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46093
46315,16017,SD,20010203,1,I-29,NaN,RURAL,SD,99,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46316,15968,SD,19990120,1,I-90,NaN,RURAL,SD,99,2.0,0,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46317,15953,SD,20010203,1,I-29,NaN,RURAL,SD,103,7.0,0,1,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,46,46103

For simplicity we will start with fatalities as our initial truck parking accident of interest.

In [10]:
county_change_df

,Unnamed: 0,COUNTY,change_2007,change_2008,change_2015,change_2016,change_2006_2016
0,0,1001,0.0,0.0,0.0,0.0,0.0
1,1,1003,-1.0,0.0,0.0,0.0,-2.0
2,2,1005,0.0,0.0,0.0,0.0,1.0
3,3,1007,0.0,0.0,0.0,0.0,1.0
4,4,1009,0.0,0.0,0.0,0.0,-1.0
...,...,...,...,...,...,...,...
2258,2258,56037,-1.0,0.0,-1.0,1.0,-1.0
2259,2259,56039,0.0,0.0,0.0,0.0,0.0
2260,2260,56041,0.0,0.0,0.0,0.0,0.0
2261,2261,56043,0.0,-1.0,0.0,0.0,-1.0
2262,2262,56045,0.0,0.0,0.0,0.0,0.0

In [11]:

# county_change_df['change_2007+2008'] = county_change_df[['change_2007', 'change_2008']].sum(axis=1)
# county_change_df['change_2015+2016'] = county_change_df[['change_2015', 'change_2016']].sum(axis=1)
#county_change_df.drop(columns=['change_2007', 'change_2008', 'change_2015', 'change_2016'], inplace=True)
# county_change_df
fatalities_filtered_df
fatalities_filtered_df.drop(columns=['VEHICLES_IN_ACCIDENT', 'INJURIES'], inplace=True)
fatalities_filtered_df

C:\Users\clint\AppData\Local\Temp\ipykernel_17952\3776773718.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fatalities_filtered_df.drop(columns=['VEHICLES_IN_ACCIDENT', 'INJURIES'], inplace=True)

,CRASH_ID,REPORT_STATE,REPORT_DATE,REPORT_SEQ_NO,LOCATION,CITY_CODE,CITY,STATE,COUNTY_CODE,FATALITIES,CRASH_EVENT_SEQ_ID_DESC,STATE_FIPS,FIPS
0,4860792,CA,20241017,1,34.441682 / -118.568696,NaN,SANTA CLARITA,CA,37,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,6,06037
1,4860781,CA,20241117,1,ANNADALE AV / 26 FT W J ST,NaN,SANGER,CA,19,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,6,06019
2,4860550,ID,20241206,2,DIVIDE CREEK,NaN,MERIDIAN,ID,1,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16,16001
3,4860541,ID,20241122,1,BEST BUSINESS AVE,NaN,KUNA,ID,1,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,16,16001
4,4860302,IL,20241205,2,S WEST ST,NaN,Olney Twp,IL,159,0,2:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,17,17159
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46313,16220,SD,19970923,1,6TH ST,NaN,SIOUX FALLS,SD,99,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46314,16111,SD,20000716,1,I-90,NaN,RURAL,SD,93,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46093
46315,16017,SD,20010203,1,I-29,NaN,RURAL,SD,99,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46316,15968,SD,19990120,1,I-90,NaN,RURAL,SD,99,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE,46,46099
46317,15953,SD,20010203,1,I-29,NaN,RURAL,SD,103,0,1:14:COLLISION INVOLVING PARKED MOTOR VEHICLE;...,46,46103

In [12]:
# Ensure COUNTY column is 5 digits
county_change_df['COUNTY'] = county_change_df['COUNTY'].astype(str).str.zfill(5)
county_change_df

,Unnamed: 0,COUNTY,change_2007,change_2008,change_2015,change_2016,change_2006_2016
0,0,01001,0.0,0.0,0.0,0.0,0.0
1,1,01003,-1.0,0.0,0.0,0.0,-2.0
2,2,01005,0.0,0.0,0.0,0.0,1.0
3,3,01007,0.0,0.0,0.0,0.0,1.0
4,4,01009,0.0,0.0,0.0,0.0,-1.0
...,...,...,...,...,...,...,...
2258,2258,56037,-1.0,0.0,-1.0,1.0,-1.0
2259,2259,56039,0.0,0.0,0.0,0.0,0.0
2260,2260,56041,0.0,0.0,0.0,0.0,0.0
2261,2261,56043,0.0,-1.0,0.0,0.0,-1.0
2262,2262,56045,0.0,0.0,0.0,0.0,0.0

In [13]:
fatalities_filtered_df = fatalities_filtered_df[['REPORT_DATE', 'FATALITIES', 'FIPS', 'STATE']]
fatalities_filtered_df

       REPORT_DATE  FATALITIES   FIPS STATE
0         20241017           0  06037    CA
1         20241117           0  06019    CA
2         20241206           0  16001    ID
3         20241122           0  16001    ID
4         20241205           0  17159    IL
...            ...         ...    ...   ...
46313     19970923           0  46099    SD
46314     20000716           0  46093    SD
46315     20010203           0  46099    SD
46316     19990120           0  46099    SD
46317     20010203           0  46103    SD

[46155 rows x 4 columns]

In [14]:
county_change_df.drop(columns=['Unnamed: 0'], inplace=True)
county_change_df

,COUNTY,change_2007,change_2008,change_2015,change_2016,change_2006_2016
0,01001,0.0,0.0,0.0,0.0,0.0
1,01003,-1.0,0.0,0.0,0.0,-2.0
2,01005,0.0,0.0,0.0,0.0,1.0
3,01007,0.0,0.0,0.0,0.0,1.0
4,01009,0.0,0.0,0.0,0.0,-1.0
...,...,...,...,...,...,...
2258,56037,-1.0,0.0,-1.0,1.0,-1.0
2259,56039,0.0,0.0,0.0,0.0,0.0
2260,56041,0.0,0.0,0.0,0.0,0.0
2261,56043,0.0,-1.0,0.0,0.0,-1.0
2262,56045,0.0,0.0,0.0,0.0,0.0

In [15]:
import pandas as pd

# Drop rows with NaN values in fatalities_filtered_df
fatalities_filtered_df.dropna(subset=['FIPS'], inplace=True)

# Drop rows with NaN values in COUNTY column of county_change_df
county_change_df.dropna(subset=['COUNTY'], inplace=True)
fatalities_filtered_df
county_change_df

C:\Users\clint\AppData\Local\Temp\ipykernel_17952\1950200917.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fatalities_filtered_df.dropna(subset=['FIPS'], inplace=True)

,COUNTY,change_2007,change_2008,change_2015,change_2016,change_2006_2016
0,01001,0.0,0.0,0.0,0.0,0.0
1,01003,-1.0,0.0,0.0,0.0,-2.0
2,01005,0.0,0.0,0.0,0.0,1.0
3,01007,0.0,0.0,0.0,0.0,1.0
4,01009,0.0,0.0,0.0,0.0,-1.0
...,...,...,...,...,...,...
2258,56037,-1.0,0.0,-1.0,1.0,-1.0
2259,56039,0.0,0.0,0.0,0.0,0.0
2260,56041,0.0,0.0,0.0,0.0,0.0
2261,56043,0.0,-1.0,0.0,0.0,-1.0
2262,56045,0.0,0.0,0.0,0.0,0.0

In [16]:
# Merge the dataframes on COUNTY and COUNTY_CODE
merged_df = pd.merge(fatalities_filtered_df, county_change_df, left_on='FIPS', right_on='COUNTY')
merged_df

,REPORT_DATE,FATALITIES,FIPS,STATE,COUNTY,change_2007,change_2008,change_2015,change_2016,change_2006_2016
0,20241017,0,06037,CA,06037,0.0,0.0,-2.0,0.0,-6.0
1,20241117,0,06019,CA,06019,0.0,-1.0,0.0,0.0,1.0
2,20241206,0,16001,ID,16001,0.0,0.0,0.0,0.0,0.0
3,20241122,0,16001,ID,16001,0.0,0.0,0.0,0.0,0.0
4,20241205,0,17159,IL,17159,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
41590,19970923,0,46099,SD,46099,1.0,0.0,0.0,-1.0,-1.0
41591,20000716,0,46093,SD,46093,2.0,0.0,0.0,1.0,5.0
41592,20010203,0,46099,SD,46099,1.0,0.0,0.0,-1.0,-1.0
41593,19990120,0,46099,SD,46099,1.0,0.0,0.0,-1.0,-1.0
41594,20010203,0,46103,SD,46103,0.0,0.0,0.0,0.0,0.0

In [17]:
import pandas as pd

# Convert REPORT_DATE to datetime
merged_df['REPORT_DATE'] = pd.to_datetime(merged_df['REPORT_DATE'], format='%Y%m%d')
# Create indicator columns
merged_df['indicator_2002_2006'] = merged_df['REPORT_DATE'].apply(lambda x: 1 if 2002 <= x.year <= 2006 else 0)
merged_df['indicator_1999_2001'] = merged_df['REPORT_DATE'].apply(lambda x: 1 if 1999 <= x.year <= 2001 else 0)
merged_df['indicator_1993_1998'] = merged_df['REPORT_DATE'].apply(lambda x: 1 if 1993 <= x.year <= 1998 else 0)

merged_df

,REPORT_DATE,FATALITIES,FIPS,STATE,COUNTY,change_2007,change_2008,change_2015,change_2016,change_2006_2016,indicator_2002_2006,indicator_1999_2001,indicator_1993_1998
0,2024-10-17,0,06037,CA,06037,0.0,0.0,-2.0,0.0,-6.0,0,0,0
1,2024-11-17,0,06019,CA,06019,0.0,-1.0,0.0,0.0,1.0,0,0,0
2,2024-12-06,0,16001,ID,16001,0.0,0.0,0.0,0.0,0.0,0,0,0
3,2024-11-22,0,16001,ID,16001,0.0,0.0,0.0,0.0,0.0,0,0,0
4,2024-12-05,0,17159,IL,17159,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41590,1997-09-23,0,46099,SD,46099,1.0,0.0,0.0,-1.0,-1.0,0,0,1
41591,2000-07-16,0,46093,SD,46093,2.0,0.0,0.0,1.0,5.0,0,1,0
41592,2001-02-03,0,46099,SD,46099,1.0,0.0,0.0,-1.0,-1.0,0,1,0
41593,1999-01-20,0,46099,SD,46099,1.0,0.0,0.0,-1.0,-1.0,0,1,0
41594,2001-02-03,0,46103,SD,46103,0.0,0.0,0.0,0.0,0.0,0,1,0

In [18]:
merged_df=merged_df.drop(columns=['FIPS'])

In [19]:
merged_df.to_csv('df_2.csv', index=False)